language: python

python:
  - "3.5"

# command to install dependencies
install:

# command to run tests
script:
  - ./build.sh
  - pip install dist/*
  - ./test/draw.py
  - ./test/transform.py
  - ./test/polygon.py
  - pip uninstall -y blocksWorld
