language: python

python:
  - "3.5"

# command to install dependencies
install:
  - apt-get install -y python3-setuptools

# command to run tests
script:
  - ./build.sh
  - pip install dist/*
  - pip uninstall -y blocksWorld
